version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      NODE_ENV: test
      LOG_LEVEL: debug
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: postgres
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema/:/docker-entrypoint-initdb.d/:ro
