version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-info}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USER: "${DATABASE_USER}"