version: "3"
services:
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./schema/:/docker-entrypoint-initdb.d/:ro
